<a href="https://colab.research.google.com/github/fininsight/text-mining-tutorial/blob/master/1_%EB%8B%A8%EC%96%B4%EC%9D%98_%ED%91%9C%ED%98%84_Word_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 단어의 표현 (Word Representation)


*   기계는 문자를 그대로 인식할 수 없기때문에 숫자로 변환



# 1 원-핫 인코딩 (One-Hot Encoding)
* 단어 집합 갯수 만큼 

## 1.1 "원숭이, 바나나, 사과" 로 원-핫 인코딩을 한다면

In [0]:
# 인코딩 대상 단어들을 담은 리스트
word_ls = ['원숭이','바나나','사과']

In [0]:
from collections import defaultdict
import numpy as np 

def one_hot_encode(word_ls):
    # 고유 단어와 인덱스를 매칭시켜주는 사전 생성
    word2idx_dic = defaultdict(lambda:len(word2idx_dic)) 
    
    # {단어 : 인덱스} 사전 구축
    for word in word_ls:
        word2idx_dic[word]
    
    n_unique_words = len(word2idx_dic) # 고유한 단어의 갯수
    one_hot_vectors = np.zeros((len(word_ls), n_unique_words)) # 원핫-벡터를 만들기 위해 비어있는 벡터 생성
    
    for i,word in enumerate(word_ls):
        index = word2idx_dic[word] # 해당 단어의 고유 인덱스
        one_hot_vectors[i, index] += 1 # 해당 단어의 고유 인덱스에만 1을 더해줌
        
    return one_hot_vectors

In [29]:
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 1.2 "코끼리"라는 단어가 추가된다면?

In [0]:
word_ls = ['원숭이','바나나','사과','코끼리']

In [31]:
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 1.3 sklearn을 활용한 one-hot encoding


함수명 | 설명
--|--
fit(X[, y])	| Fit OneHotEncoder to X.
fit_transform(X[, y])	| Fit OneHotEncoder to X, then transform X.
inverse_transform(X)	| Convert the back data to the original representation.
transform(X)	| Transform X using one-hot encoding.

In [32]:
# sklearn을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(word_ls)
print(values)

# 문자열에 숫자를 붙임
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
print(int_enc)

# binary encode
onehot_enc = OneHotEncoder(sparse=False)
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 matrix로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

# one-hot encoding 의 첫번째 배열을 값을 역으로 산출
inverted = label_enc.inverse_transform([argmax(onehot_enc[0, :])])
print(inverted)

['원숭이' '바나나' '사과' '코끼리']
[2 0 1 3]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['원숭이']


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)




---



# 2 밀집 벡터 (Dense Vector)

In [0]:
word_embedding_dic = {
    '사과' : [1.0, 0.5],
    '바나나' : [0.9, 1.2],
    '원숭이' : [0.5, 1.5]
}



---



# 3 유사도 계산

## 3.1 유클리디언 거리(Euclidean distance)

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/220px-Euclidean_distance_2d.svg.png"  width="200"/>

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/795b967db2917cdde7c2da2d1ee327eb673276c0" width="350"/>

https://en.wikipedia.org/wiki/Euclidean_distance

In [49]:
import numpy as np
def dist(x,y):   
    x = np.array(x)
    y = np.array(y)
    return np.sqrt(np.sum(x-y)**2)
  
# 사과와 바나나의 코사인 유사도
dist(word_embedding_dic['사과'], word_embedding_dic['바나나'])

0.6

## 3.2 마할라노비스 거리(Mahalanobis distance)

## 3.3 민코스키 거리(Minkowski distance)

## 3.4 코사인 유사도(Cosine Similarity) 계산

In [0]:
def cal_cosine_similarity(x, y):
    # x와 y, 두 벡터의 코사인 유사도를 계산하는 함수
    nominator = np.dot(x, y)    # 분자
    denominator = np.linalg.norm(x)*np.linalg.norm(y)  # 분모
    return nominator/denominator

In [0]:
# 사과와 바나나의 코사인 유사도
cal_cosine_similarity(word_embedding_dic['사과'], word_embedding_dic['바나나'])

0.8944271909999159

In [0]:

# 사과와 원숭이의 코사인 유사도
cal_cosine_similarity(word_embedding_dic['사과'], word_embedding_dic['원숭이'])

0.7071067811865475

In [0]:
# 바나나와 원숭이의 코사인 유사도
cal_cosine_similarity(word_embedding_dic['바나나'], word_embedding_dic['원숭이'])

0.9486832980505138



---



# 4 단어 임베딩 (Word Embedding)

## 4.1 구글드라이브 내 파일 읽어오기

In [0]:
# 구글 드라이브에서 csv 파일을 읽어오기 위해 gauth 인증을 합니다.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
url_it ='https://drive.google.com/open?id=1Yj9sJ-E_ZiOmEcHpsHI7-iIvs08HEVNN'
id_it = url_it.split('=')[1]
print(id_it)

url_culture ='https://drive.google.com/open?id=1eG0Tdh3b27Su5Zt45LXdBS3sHe2kDb7x'
id_culture = url_culture.split('=')[1]
print(id_culture)

1Yj9sJ-E_ZiOmEcHpsHI7-iIvs08HEVNN
1eG0Tdh3b27Su5Zt45LXdBS3sHe2kDb7x


In [0]:
%ls

adc.json  실리콘벨리기사_전처리.csv  sample_data/


In [0]:
# 크롤링해 온 국민청원 데이터를 판다스를 통해 읽어온다.
downloaded = drive.CreateFile({'id':id_it}) 
downloaded.GetContentFile('2_word_embedding_it.csv')  

# 크롤링해 온 국민청원 데이터를 판다스를 통해 읽어온다.
downloaded = drive.CreateFile({'id':id_culture}) 
downloaded.GetContentFile('2_word_embedding_culture.csv')  

In [0]:
%ls

2_word_embedding_culture.csv  2_word_embedding_it.csv  adc.json  sample_data/


In [0]:
import pandas as pd
it_df = pd.read_csv('2_word_embedding_it.csv').dropna()
culture_df = pd.read_csv('2_word_embedding_culture.csv').dropna()

## 4.2 Word2Vec

In [0]:
it_token_ls = list(it_df.loc[:,'1'])
culture_token_ls = list(culture_df.loc[:,'1'])
total_token_ls = it_token_ls + culture_token_ls

In [0]:
total_token_ls[0]

'배,정회,신임,과학기술,일자리,진흥,원장,아시아,경제,이민,우,배,정회,전,국립,중앙,과학,관,전시,연구,단장,과학기술,일자리,진흥,제,원장,취임,과학기술,정보,통신,같은,인사,발표,임기,날,동안,배,신임,원장,행정,고등고시,공직,입문,교육,과학기술,부,융합,기술,과장,중앙대,경영,경제,초빙교수,과기,정통부,연구,성과,활용,정책,과장,연구,성과,혁신,기획,과장,과학기술,정책,수립,정부,연구개발,연구,기술,이전,사업,두루,경험,보유,평가,배,신임,원장,날,환담,회,새로운,임무,조직,신속히,성하고,직원,역량,강화하겠다,며,실험실,유망,기술,전,문,기업,연결하며,기술,이전,효과,지원,신,기술,창업,통한,미래,일자리,많이,창,고,이민,우,네이버,홈,아시아,경제,뉴스,확인,재미,신기,과학,꿀,잼,인,기,만화,경제,눈,세계,창,아시아,경제,전,재'

In [0]:
total_token_ls = [tokens.split(',') for tokens in total_token_ls]

In [0]:
total_token_ls[0][:10]

['배', '정회', '신임', '과학기술', '일자리', '진흥', '원장', '아시아', '경제', '이민']

In [0]:
!pip install paramiko
from gensim.models import Word2Vec

    100% |████████████████████████████████| 194kB 7.0MB/s 
    100% |████████████████████████████████| 2.3MB 9.3MB/s 
    100% |████████████████████████████████| 61kB 23.6MB/s 
    100% |████████████████████████████████| 768kB 19.4MB/s 
    100% |████████████████████████████████| 102kB 29.9MB/s 


In [0]:
word2vec = Word2Vec(
    sentences = total_token_ls,  # 학습시킬 문장
    size = 30,                  # 임베딩된 단어 벡터의 차원 크기
    alpha = 0.025,               # 학습률(Learning rate)
    min_count=2,                 # 1번 미만 등장한 단어는 제외
    window = 8,                  # 문맥의 크기 (window_size)
    sample = 0.001,              # sub-sampling
    sg = 1,                      # 0: CBOW, 1: Skip-gram
    iter = 10,                    # 전체 문장 반복학습 횟수(epoch)
    )

In [0]:
word2vec.wv.__getitem__('문화')

array([ 0.7587959 , -0.11468028,  0.99950695, -0.5830294 , -0.53146863,
       -0.08724304, -0.04303695,  0.44012544, -0.2901832 ,  0.47357106,
       -0.6258593 ,  0.22127847,  0.5892466 ,  0.46860823,  0.34110332,
        0.62596506, -0.57041854, -0.56690645,  0.53896487, -0.967613  ,
       -0.8699213 , -0.52416694, -0.72738206, -0.4006263 , -1.0287417 ,
       -0.44523874, -0.4051323 , -0.04418683,  0.5541464 , -0.05710315],
      dtype=float32)

In [0]:
word2vec.wv.most_similar('인공')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('지능', 0.9658249616622925),
 ('유전자', 0.866620659828186),
 ('학습', 0.8557372093200684),
 ('높아', 0.8464064002037048),
 ('접목', 0.8357588648796082),
 ('결합', 0.8341535329818726),
 ('핀란드', 0.8224778175354004),
 ('정확성', 0.8214777708053589),
 ('프로젝트', 0.8140239119529724),
 ('의료', 0.8072370290756226)]

In [0]:
word2vec.wv.most_similar('공연')

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('회관', 0.9334250688552856),
 ('예술', 0.925646185874939),
 ('평양', 0.910593569278717),
 ('극장', 0.9045096635818481),
 ('관현악단', 0.8928622603416443),
 ('국악', 0.8884977102279663),
 ('그림', 0.8862243890762329),
 ('클래식', 0.8840991258621216),
 ('기원', 0.8784158229827881),
 ('연주', 0.8696287274360657)]

In [0]:
culture_df

Unnamed: 0                                                  0  \
0             0  "[안성완 인턴기자 asw0727@imaeil.com] 사진=위메프 홈페이지 캡쳐위...   
1             1  "울산과 경남, 경북, 강원, 제주 등 5개 시도에서 공공 부문 중심 미세먼지 비상...   
2             2  "한국방송통신대학교(총장 류수노/이하 방송대)가 1월19일 ‘제 1회 KNOU 글로...   
3             3  "배우 박환희. [사진 박환희 인스타그램]      배우 박환희(29)가 섬유근육통...   
4             4  "ㆍ두 얼굴의 문명, 그 너머를 위해이탈리아 로마 근교 아피아 가도에는 아직도 수레...   
5             5  "(서울=연합뉴스) 서울 종로구 부암동 서울미술관이 22일 기자간담회를 열고 신관을...   
6             6  "(서울=연합뉴스) 국립중앙박물관은 22일 손혜원 의원 관련 의혹을 해명하면서 작년...   
7             7                                            "동영상 뉴스   
8             8  \t지난 20일 <SBS스페셜>을 통해 소개된 단식모방식단 FMD(Fasting-M...   
9             9  "자료로 짚어본 한글과 여성“국문(한글)이 생긴 후 제일가는 명필”이란 극찬을 받은...   
10           10  ""작년 6월 손 의원이 '추천'…검토했으나 하지는 않아""나전칠기도 구입 검토했지...   
11           11                                            "동영상 뉴스   
12           12  \t오늘(22일) 소양강에 올겨울 첫 상고대가 피어났습니다.상고대는 서리가 얼어붙는...   
13           13  "권용집 홍콩관광청 지사장【서울=뉴시스】신효령 기자 = "50대가 해외여행 주류로 ...   
14           14  "국립무용단 '북의 시나위' 중 '진도북' ⓒ국립극장 【서울=뉴시스】 이재훈 기자 ...   
15           15  "울산시, 가족 추정 6마리 관측울산 태화강을 찾는 겨울 철새가 꾸준히 늘고 있는 ...   
16           16  "(세종=연합뉴스) SM상선 신임 대표에 박기훈 부사장. 2019.1.22 [SM상...   
17           17                                            "동영상 뉴스   
18           18  \t아카데미 오늘 후보 발표…'버닝' 본선 갈까[앵커]지난해 최고의 영화를 뽑는 아...   
19           19  "(세종=연합뉴스) 김동규 기자 = SM상선 신임 대표이사로 박기훈 부사장이 선임됐...   
20           20  "[원불교 제공](서울=연합뉴스) 강종훈 기자 = 원불교 은산 김장원 원정사가 지난...   
21           21  "낮부터 포근…미세먼지 주의 (CG)[연합뉴스TV 제공](서울=연합뉴스) 정래원 기...   
22           22  "북한과 영국, 벨기에의 합작영화 ‘김동무는 하늘을 난다’의 한 장면. 연합뉴스부산...   
23           23  "개성 만월대 발굴 대상지 모습. 연합뉴스남북 문화교류 분야에서 문화유산 분야의 지...   
24           24  "손혜원 의원이 다른 기관에 근무하는 특정 학예직 인사를 국립중앙박물관(국박)에서 ...   
25           25  "행맨(23일 개봉)◆ 영화행맨(23일 개봉)감독: 자니 마틴출연: 알 파치노, 칼...   
26           26                                            "동영상 뉴스   
27           27   [앵커] 손혜원 의원 관련 의혹의 핵심중 하나는 법률을 고치거나 만들 수 있는 국...   
28           28  "[일간스포츠 이승한기자]  강남 ANC지상직학원이  오는 3월부터 시작되는 상반기...   
29           29  "박물관 세가지 의혹에 대해 해명했지만 논란은 여전 "손혜원 학예사 인사 요구 있었...   
..          ...                                                ...   
77           77  "ⓒ동작구청서울 동작구(구청장 이창우)가 관내 저소득층 여성청소년의 건강한 성장을 ...   
78           78  "[일간스포츠 온라인]  성장기 어린이들에게 장 건강은 매우 중요하다. 장 운동이 ...   
79           79  "21일 '킹덤' 제작보고회배우 배두나가 21일 서울 삼성동 코엑스인터컨티넨탈호텔에...   
80           80  "▶매경 뉴스레터 '매콤달콤'을 지금 구독하세요▶뉴스 이상의 무궁무진한 프리미엄 읽...   
81           81  "강민혁씨 철학책 서평집 '자기배려의 책읽기' 출간[교보문고 홈페이지](서울=연합뉴...   
82           82  ""강원 영동 제외 이달 말까지 눈 안 와"작년 12월~이달 21일, 평균 적설 적...   
83           83  "정신우 셰프가 16일 서울 강남구 한 카페에서 최근 출간한 에세이집 ‘먹으면서 먹...   
84           84  "첫 작품에 유광수 작가의 '싱글몰트 사나이 1, 2'유광수 작가(서울=연합뉴스) ...   
85           85  "메디힐 ‘올리브영 헬스&뷰티 어워즈’서 2년 연속 1위 수상 © 뉴스1(서울=뉴스...   
86           86  "━   [더,오래] 전구~욱 손주자랑(35)      눈에 넣어도 아프지 않은 손...   
87           87  "목포 수산도시 조성사업 정부차원 적극 지원 밝혀"근대역사문화공원 사업 논란 법대로...   
88           88  "[조두진 기자 earful@imaeil.com] 다행히도 재주 없어 책 표지고려시...   
89           89  "긍정 한국이미지 동남아선 90%, 일본선 20% 해외문화홍보원 국가이미지 조사…외...   
90           90  "광주·강릉 등은 적설량 '0'…가뭄 우려는 없어최근 한반도에 눈이 적은 원인[기상...   
91           91  "(서울=연합뉴스) 남편 동생은 도련님 혹은 아가씨로 부르고, 부인 동생은 처남 혹...   
92           92  "▲ 오산시청 전경. / 사진제공=오산시보건복지부 선정 보육정책 우수 지자체인 오산...   
93           93  "이낙연 국무총리가 22일 오후 전남 목포시 수산식품지원센터에서 발언하고 있다.20...   
94           94  "[머니투데이 함혜강 에디터] 화실과공방 앱 /사진제공=에프피에이주식회사 에프피에이...   
95           95  "(서울=연합뉴스) 강성철 기자 = "식당에서 왜 고기를 가위로 자르나요?"    ...   
96           96  "(서울=연합뉴스) 설을 전후한 다음달 4~6일 전국 고속도로 통행료가 면제되고 역...   
97           97  "10세기 제작, 전기 불교조각 지방양식 보여줘명문으로 985년 조성 확실…고려 전...   
98           98  "곡성 죽동농악 주제로 전시회[곡성군 제공]    (곡성=연합뉴스) 박철홍 기자 =...   
99           99  "한국문화재재단 진옥섭 이사장(왼쪽)과 국립국악원 임재원 원장[한국문화재재단 제공]...   
100         100  "구세군 설맞이 사랑의 쌀 나눔 활동[구세군 제공]    ▲ 구세군은 설을 맞아 소...   
101         101  "미세먼지를 잡아먹는 해초로 알려진 곰피가 화제다. 청정지역 충남 태안의 앞바다에서...   
102         102

## 4.3 차원축소 활용 시각화